version: "3"
services:
  app:
    container_name: docker-node-mongo
    restart: always
    environment:
      - MONGODDB_USER="kodokuAdmin"
      - MONGODB_PASSWORD="Rt4yi21f"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    build: .
    ports:
      - "8085:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    command: [--auth]
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodata:
